baseURL                 = 'https://new.wecamp.pro/'
canonifyurls            = "true"
languageCode            = 'fa-ir'
title                   = 'وی‌کمپ، کمپ‌های حرفه‌ای'
publishDir              = "docs"

[permalinks]
    about-us             = "/:section/:contentbasename/"  #why :contentbasename, why not :title? not to break the return link in shop page; Better to use another idea by coding a bit in future.
    blog                = "/:section/:year/:month/:title/"
    apply                 = "/:section/:contentbasename/"
    something_else                = "/:title/"

[[cascade]]
   [cascade._target]
    path = '/camps/product-design-1'
    [cascade.params]
      layout = "product-design-1"
[[cascade]]
   [cascade._target]
    path = '/camps/cloud-infra-1'
    [cascade.params]
      layout = "cloud-infra-1"
[[cascade]]
   [cascade._target]
    path = '/camps/cloud-infra-2'
    [cascade.params]
      layout = "cloud-infra-2"

[[cascade]]
   [cascade._target]
    path = '/camps/price'
    [cascade.params]
      layout = "price"
